### ISSUE TITLE
Implement a simple Auth to replace Azure AD

### ISSUE THREAD

**Issue by fcatae** [DXBrazil/Arda#23]
Azure AD requires specific configurations (ReplyURL and HTTPS) very challenging for the initial deployment -- see #18. We need a simpler mechanism for Auth to start with. Later the user may configure AzureAD and use the proper credentials.

**Comment by allantargino** [comment]
Online OAuth methods, using Azure AD or not, will always require a reply URL (it is a behaviour by design). So changing to another OAuth implementation may not be the best way.
The other challenge is that we should use a native ASP.NET authentication method, since almost all controllers are decored with [Authorize] attribute.
We may start with: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple

**Comment by allantargino** [comment]
Another idea to test it's to incorporate an OAuth authentication server in one microservice (I would choose Permissions service). As soon as all containers are running, the local server will be there too.
https://blogs.msdn.microsoft.com/webdev/2016/10/27/bearer-token-authentication-in-asp-net-core/

**Comment by fcatae** [comment]
Ref: 
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie
https://github.com/leastprivilege/AspNetCoreSecuritySamples/blob/master/Authorization/src/AspNetCoreAuthentication/Startup.cs
