### ISSUE TITLE
Hidden Exceptions

### ISSUE THREAD

**Issue by lucaslra** [DXBrazil/Arda#4]
Hello again,

Crawling through the code I found a considerable number of exceptions handled in a very generic way like

```csharp
try{ 
//...
}
catch (Exception) { return null; }
```

In my experience, that can be a big problem to troubleshoot in case of a serious problem.
So, I have two suggestions to soften this problem:
1) Those exception should probably be logged in someform
2) The catch scope should be reduced, at least to ApplicationException

Is this viable?

**Comment by ViniciusSouza** [comment]
You are absolutely right. 
We will create a new branch for it to make it easy to work in the project rather than keep the changes in the master.

**Comment by fcatae** [comment]
We are going to remove these exception handling code because they add no value. And later we add the Application Insight to handle it using ASP.NET middlewares.

**Comment by fcatae** [comment]
We still have some try/catch in the code that can't be removed because
- the code relies on this behavior  -OR-
- it is too dangerous to remove it at this time

We will apply @lucaslra recommendations:
1 - Log the exceptions - see issue #15, which we will use Application Insight to capture the exceptions
2 - Reduce the scope (use a derived class instead of the generic Exception class)

**Comment by fcatae** [comment]
Finish the work - we had many places to test. Combined with AppInsights to cover some edge cases
